server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:13306/roomy?serverTimezone=UTC&characterEncoding=UTF-8
    username: roomy
    password: backend
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true