server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/roomy?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: roomy
    password: backend
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always